services:
  backend:
    build:
      context: ./backend
    container_name: workflow_backend
    ports:
     - "8000:8000"
  volumes:
    - ./backend:/app
  restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: workflow_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped